import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const assetVersions = {};
for (const asset of ['styles.css', 'books.js', 'music.js', 'art.js']) {
 assetVersions[asset] = createHash('sha256').update(await readFile(new URL(asset, import.meta.url))).digest('hex').slice(0,12);
}
const content = JSON.parse(await readFile(new URL('content.json', import.meta.url), 'utf8'));
const albums = JSON.parse(await readFile(new URL('albums.json', import.meta.url), 'utf8'));
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link = value => { if (!value) return ''; const url = new URL(value); if (!['https:', 'http:'].includes(url.protocol)) throw new Error('Links must use HTTP or HTTPS'); return esc(url.href); };
const sections = [['books','Books'],['music','Music'],['essays','Essays'],['art','Art'],['sports','Sports']];
const favicon = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='18' fill='%23322348'/%3E%3Ctext x='32' y='46' text-anchor='middle' font-family='Georgia' font-size='49' fill='white'%3Er%3C/text%3E%3C/svg%3E";
function page(slug, title, body, description, script = '') {
 const root = slug ? '../' : './';
 return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(description)}"><title>${esc(title)} — Rime</title><link rel="icon" type="image/svg+xml" href="${favicon}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500&display=swap" rel="stylesheet"><link rel="stylesheet" href="${root}styles.css?v=${assetVersions['styles.css']}">${script ? `<script src="${root}${script}?v=${assetVersions[script]}" defer></script>` : ''}</head>
<body class="${slug || 'home'}"><a class="skip-link" href="#main">Skip to content</a><div class="shell"><header><a class="wordmark" href="${root}" aria-label="Rime, home">rime<span>.</span></a>${slug ? `<a class="back" href="${root}">← Back to my nook</a>` : ''}</header><main id="main">${body}</main><footer>${slug ? `<nav aria-label="Explore my nook">${sections.map(([path,label])=>`<a href="../${path}/"${path === slug ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav>` : '<span>A little bit of everything, really.</span>'}<span class="signature">Rime</span></footer></div></body></html>\n`;
}
const optionalLink = (url,label) => url ? `<a href="${link(url)}">${label} <span aria-hidden="true">↗</span></a>` : `<span class="pending">${label}<small>soon</small></span>`;
const bookShelf = `<section class="shelf-intro"><p class="eyebrow">A few favourites.</p><h1>My little<br><em>library.</em></h1><a class="text-link" href="${link(content.goodreads)}">My Goodreads ↗</a></section>
<div class="shelf-stage"><div class="bookshelf" role="group" aria-label="Favourite books. Select a book to see its title and author.">${content.books.map((b,i)=>`<button class="book-slot${i === 0 ? ' selected' : ''}" type="button" data-book="${i}" aria-pressed="${i === 0}" aria-label="${esc(b.title)} by ${esc(b.author)}" style="--cover:${esc(b.color)};--book-ink:${esc(b.ink)}"><span class="book-object"><span class="book-spine"><span>${esc(b.title)}</span><small>${esc(b.author)}</small></span><span class="book-front"><small>${esc(b.author)}</small><strong>${esc(b.title)}</strong><span class="cover-rule"></span><span class="book-edition">Rime's library</span></span></span></button>`).join('')}</div></div>
<section class="book-detail" aria-label="Selected book"><div aria-live="polite" aria-atomic="true"><p class="eyebrow" id="book-count">01 / ${String(content.books.length).padStart(2,'0')}</p><h2 id="book-title">${esc(content.books[0]?.title || '')}</h2><p id="book-author">${esc(content.books[0]?.author || '')}</p></div><div class="shelf-controls" hidden><button type="button" id="previous-book" aria-label="Previous book" disabled>←</button><button type="button" id="next-book" aria-label="Next book">→</button></div></section>`;
await writeFile(new URL('index.html',import.meta.url),page('', 'My little nook', `
<section class="home-intro"><p class="eyebrow">Hi, I'm Rime.</p><h1>Welcome to my little<br><em>nook</em> of the internet.</h1><p class="bio">23. Studying computer science.<br>Living between France and Germany.</p></section>
<nav class="directory" aria-label="My corners of the internet">${sections.map(([path,label],i)=>`<a href="${path}/"><span class="number">0${i+1}</span><span>${label}</span><span class="go" aria-hidden="true">↗</span></a>`).join('')}<div class="directory-external"><span class="number">0${sections.length+1}</span>${optionalLink(content.letterboxd,'Movies on Letterboxd')}</div></nav>
<nav class="elsewhere" aria-label="Elsewhere"><a href="https://github.com/rime3-14">GitHub <span aria-hidden="true">↗</span></a>${optionalLink(content.portfolio,'Portfolio')}</nav>`, "Rime's little nook: books, music, writing, art, and sport."));
const firstAlbum = albums[0];
const artGallery = `<section class="art-heading"><h1>Art.</h1><p>Hover or tap a piece.</p></section>
<section class="gallery" aria-label="Favourite artworks">${content.art.map((a,i)=>`<article class="art-card"><button type="button" class="art-toggle" aria-pressed="false" aria-label="Details: ${esc(a.title)}" aria-describedby="art-details-${i}"><span class="art-inner"><span class="art-front" aria-hidden="false"><img src="${link(a.image)}" alt="${esc(a.alt)}" loading="${i<3?'eager':'lazy'}" decoding="async" referrerpolicy="no-referrer"></span><span class="art-back" id="art-details-${i}" aria-hidden="true"><strong>${esc(a.title)}</strong><span class="art-artist">${esc(a.artist)}</span><span class="art-date">${esc(a.date)}</span><span class="art-location"><small>Collection / location</small>${esc(a.location)}</span>${a.note ? `<span class="art-note">${esc(a.note)}</span>` : ''}</span></span></button></article>`).join('')}</section>
<details class="art-sources"><summary>Artwork sources & credits</summary><p>Collection details don’t necessarily mean a work is currently on display.</p><ul>${content.art.map(a=>`<li><a href="${link(a.source)}">${esc(a.title)} ↗</a>${a.credit ? `<span>${esc(a.credit)}</span>` : ''}${a.imageSource ? `<a href="${link(a.imageSource)}">Photograph source</a> · <a href="${link(a.license)}">License</a>` : ''}</li>`).join('')}</ul></details>`;
const musicPage = `<section class="music-heading" aria-live="polite" aria-atomic="true"><p class="eyebrow">On the turntable</p><h1 id="album-title">${esc(firstAlbum.title)}</h1><p id="album-artist">${esc(firstAlbum.artist)}</p></section>
<div class="listening-room"><aside class="album-shelf" aria-label="Choose an album">${albums.map((a,i)=>`<button type="button" class="album-choice" aria-label="${esc(a.title)} by ${esc(a.artist)}" aria-pressed="${i===0}" title="${esc(a.title)} — ${esc(a.artist)}" data-title="${esc(a.title)}" data-artist="${esc(a.artist)}" data-cover="${link(a.cover)}" data-track="${esc(a.track)}" data-preview="${link(a.preview)}" data-url="${link(a.trackUrl)}"><img src="${link(a.cover)}" width="100" height="100" alt="" loading="eager"></button>`).join('')}</aside>
<div class="turntable"><div class="record" id="record" role="img" aria-label="A vinyl record with the ${esc(firstAlbum.title)} album cover at its centre"><div class="record-label"><img id="record-cover" src="${link(firstAlbum.cover)}" width="100" height="100" alt="${esc(firstAlbum.title)} album cover"><span class="spindle"></span></div></div></div></div>
<p class="track-name" id="track-name">${esc(firstAlbum.track)}</p><div class="record-controls"><button id="audio-toggle" type="button" aria-controls="album-audio" hidden>Play preview</button><button id="spin-toggle" type="button" aria-controls="record" hidden>Pause rotation</button><a id="listen-link" href="${link(firstAlbum.trackUrl)}">Apple Music <span aria-hidden="true">↗</span></a></div><audio id="album-audio" preload="none" src="${link(firstAlbum.preview)}"></audio><p class="audio-status" id="audio-status" role="status">Song previews · Apple Music</p>`;
const pages = {
 books: ['Books', bookShelf, 'Six favourite books from Rime’s personal library.', 'books.js'],
 fashion: ['Fashion & couture', `<section class="section-intro fashion-title"><p class="eyebrow">A personal fashion journal</p><h1>Fashion<br><span class="amp">&</span> <em>couture.</em></h1><p class="lede">The art of getting dressed.</p></section><div class="fashion-topics"><span>Silhouettes</span><span>Details</span><span>Haute couture</span></div><p class="empty-note">A collection of favourite looks and details, coming soon.</p>`, 'Rime’s fashion and haute couture journal.'],
 music: ['Music', musicPage, 'A few albums on Rime’s turntable.', 'music.js'],
 essays: ['Essays', `<section class="section-intro"><h1>In my own words.</h1></section><section class="essay-list" aria-label="Published essays">${content.essays.length ? content.essays.map(e=>`<article><h2><a href="${esc(e.slug)}.html">${esc(e.title)}</a></h2><p>${esc(e.summary || '')}</p><time datetime="${esc(e.date)}">${esc(e.date)}</time></article>`).join('') : '<p class="empty-note">Coming soon.</p>'}</section>`, 'Essays and writings by Rime.'],
 art: ['Art', artGallery, 'A gallery of Rime’s favourite artworks.', 'art.js'],
 sports: ['Sports', `<h1 class="visually-hidden">Sports</h1><div class="sports-grid"><section><h2>What I do</h2><ul><li>Yoga</li><li>Pilates</li></ul></section><section><h2>What I follow</h2><ul><li>Formula 1</li><li>Football</li></ul></section></div>`, 'Yoga, Pilates, Formula 1, and football: Rime’s sporting interests.']
};
for (const [slug,[title,body,description,script]] of Object.entries(pages)) {
 await mkdir(new URL(`${slug}/`,import.meta.url),{recursive:true});
 await writeFile(new URL(`${slug}/index.html`,import.meta.url),page(slug,title,body,description,script));
}
for (const essay of content.essays) {
 if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(essay.slug) || essay.slug === 'index') throw new Error('Invalid essay slug');
 const body = `<article class="essay-body"><a class="back" href="./">← All essays</a><h1>${esc(essay.title)}</h1><time datetime="${esc(essay.date)}">${esc(essay.date)}</time>${essay.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</article>`;
 await writeFile(new URL(`essays/${essay.slug}.html`,import.meta.url),page('essays',essay.title,body,essay.summary || essay.title));
}
console.log('Built homepage and six sections.');
